# Generated by Django 5.0.6 on 2024-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
