# Generated by Django 5.0.6 on 2024-06-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='contact_email',
        ),
    ]
