# Generated by Django 5.0.6 on 2024-07-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0002_employerprofile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rjb.employerprofile'),
        ),
    ]
