# Generated by Django 5.0.6 on 2024-07-03 18:15

import rjb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0003_alter_jobposting_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=rjb.models.employer_logo_directory_path),
        ),
    ]
