# Generated by Django 5.0.6 on 2024-07-03 22:36

import rjb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0004_alter_employerprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=rjb.models.candidate_profile_picture_directory_path),
        ),
    ]
