# Generated by Django 5.0.6 on 2024-07-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0005_alter_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='immigration_assistance',
            new_name='ISL',
        ),
    ]
