# Generated by Django 5.0.6 on 2024-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0006_rename_immigration_assistance_jobposting_isl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(blank=True, through='rjb.JobRequiresSkill', to='rjb.skill'),
        ),
    ]
