# Generated by Django 5.0.6 on 2024-07-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0007_jobposting_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='case_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rjb.caseworkerprofile'),
        ),
    ]
