# Generated by Django 5.0.6 on 2024-07-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0008_candidateprofile_case_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSavesJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rjb.candidateprofile')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rjb.jobposting')),
            ],
            options={
                'unique_together': {('candidate', 'job_posting')},
            },
        ),
    ]
