# Generated by Django 5.0.6 on 2024-07-18 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0011_application_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='scheduled_at',
        ),
        migrations.AddField(
            model_name='interview',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
