# Generated by Django 5.0.6 on 2024-07-27 20:05

import rjb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rjb', '0013_joboffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='job_offer_document',
            field=models.FileField(blank=True, null=True, upload_to=rjb.models.job_offer_document_directory_path),
        ),
    ]
